# 第10课：年份切片与摘要

本笔记本是课堂讲义。每个知识点包含：理论知识、案例代码、讲解、易错点与练习。综合练习 P1 使用同目录的 [steam.csv](steam.csv)。课后独立练习见 [chapter10_年份切片与摘要_课后练习.ipynb](chapter10_年份切片与摘要_课后练习.ipynb)，数据为 [steam_sample.csv](steam_sample.csv)。

## 学习目标

1. 说明字符串和列表一样可以切片，并用 `row[2][:4]` 取四位发行年。
2. 用第 5 课四步字典统计年份频率；年份键必须是四位年。
3. 按约定把好评数变成档位：取首位、其余补 0、再加号（`124534` → `100000+`，`3318` → `3000+`）。
4. 解释不能对 `int` 直接切片，必须先 `str()`。
5. 写出让人读得懂的一句话摘要，而不是只 dump 字典。

## 学习知识点

| 年份切片 | 档位 | 摘要 |
| --- | --- | --- |
| `date[:4]` 取年 | 首位 + 补 0 + `+` | 频数让人读得懂 |
| 四步年份频率 | `124534` → `100000+` | 不要只 dump 字典 |
| 键是四位年 | 先 `str` 再切片 | 开发者也可以四步 |

## 基础回顾与案例提问

第 9 课已经能把好评字段变成整数。整数一多，直接做频率表会得到成千上万个不同的键，读起来不像摘要。本课两件事：从 `2000-11-01` 里切出年份；把 `124534` 收成 `100000+` 这样的档。列下标仍按 Steam 表：`release_date=2`，`developer=4`，`positive_ratings=12`。换表后不要沿用移动游戏下标。

案例只用前 5 行讲语法。不要在讲义里 dump 全部年份键或全表开发者排行——那是 P1 要你自己做的。

1. **R.1** `"2000-11-01"[:4]` 是什么？它 `== "2000"` 吗？
2. **R.2** 按“首位 + 其余补 0 + 加号”，`3318` 和 `124534` 各变成什么？对整数写 `3318[0]` 会怎样？
3. **R.3** 只 `print` 一整本字典，和写“前 5 行里 Valve 开发了若干款游戏”，哪一种更像摘要？

**作答：** 预测：____；依据：____；验证后说明：____。

使用 Python 3；只需标准库 `csv`。从该文件夹启动内核。打开 CSV 使用 `encoding="utf-8-sig"`。本课不讲 pandas 排序，不展开 `sorted` 的 key 理论。不要使用列表推导式、正则或 `Counter`。年份全表频率、档位字典是否出现 `100000+`，必须由你的代码算出。


In [ ]:
# R.1–R.3: Write and verify your predictions here.


## 1. 字符串和列表一样可以切片

### 理论知识

第 3 课对列表用过 `titles[:5]`。**字符串也可以按位置切开。** `"2000-11-01"[0]` 是第一个字符 `"2"`；`"2000-11-01"[:4]` 是前四个字符 `"2000"`。

发行日期这一列的形式是 `年-月-日`。本班统一用前四位当发行年，不要在课堂上每人一种 `split` 方案。切片下标含头不含尾：`[:4]` 取到下标 0、1、2、3。

### 案例：从日期文本取出年份


In [1]:
date = "2000-11-01"
print(date[0])
print(date[:4])
print(date[:4] == "2000")
print("1999-04-01"[:4])


2
2000
True
1999


### 讲解

`"2000-11-01"[:4]` 等于 `"2000"`，比较结果为 `True`。`"1999-04-01"` 同理得到 `"1999"`。这就是后面 `row[2][:4]` 的迷你版：先取发行日期字段，再切前四位。

### 易错点与练习

`[:4]` 不是“切掉 4 个字符”，而是“留下下标 0 到 3”。日期里的 `-` 在下标 4，刚好不被取到。

1. **K1.1** `"2003-05-01"[:4]` 是什么？
2. **K1.2** `"2000-11-01"[:7]` 会含月份吗？本课为什么不用它当年份键？

**作答：** 2003 的前四位：____；切到 7 位的问题：____。


In [ ]:
# Write your predictions, reasoning, or solution here.
# Keep deliberately faulty snippets in Markdown; run your corrected code here.


## 2. 从数据行取出发行年

### 理论知识

Steam 表：`release_date` 在下标 2。取年的完整动作是 `row[2][:4]`。先读文件、认列，再只看前 5 行，避免把约 2.7 万行的年份全打出来。

若第 9 课的列常量还在，可以继续用；本笔记本应自己读取 [steam.csv](steam.csv)，不要依赖另一本课堂笔记的变量。

### 案例：前 5 行的年


In [2]:
import csv

with open("steam.csv", "r", encoding="utf-8-sig", newline="") as file:
    rows = list(csv.reader(file))
header = rows[0]
body = rows[1:]
NAME = 1
RELEASE_DATE = 2
DEVELOPER = 4
POSITIVE_RATINGS = 12
print("release_date index:", header.index("release_date"))
print("Years of first 5 rows:")
for row in body[:5]:
    year = row[RELEASE_DATE][:4]
    print(row[NAME], row[RELEASE_DATE], "->", year)


release_date index: 2
Years of first 5 rows:
Counter-Strike 2000-11-01 -> 2000
Team Fortress Classic 1999-04-01 -> 1999
Day of Defeat 2003-05-01 -> 2003
Deathmatch Classic 2001-06-01 -> 2001
Half-Life: Opposing Force 1999-11-01 -> 1999


### 讲解

前 5 行应看到 2000、1999、2003、2001、1999。第五款是 Half-Life: Opposing Force，开发者不是 Valve。本格不打印全表有多少种年份——种类数留给 P1。

### 易错点与练习

`row[2][:4]` 里先写列下标，再写字符切片。写成 `row[:4]` 切的是前 4 **列**，不是年份。

1. **K2.1** `row[:4]` 和 `row[2][:4]` 各取出什么？
2. **K2.2** 前 5 行里，哪一个年份出现了两次？

**作答：** 两种切片的对象：____；重复的年：____。


In [ ]:
# Write your predictions, reasoning, or solution here.
# Keep deliberately faulty snippets in Markdown; run your corrected code here.


## 3. 年份频率：还是那四步

### 理论知识

第 5 课四步：**空字典 → 循环 → 键不在则置 0 → +1**。第 6 课把它收进函数。本课可以重写四步，也可以自己再写一个 `freq_table`；不必从另一本笔记本 import。

键必须是四位年，例如 `"2000"`，而不是 `"2000-11-01"`，也不是 0、1、2。案例只统计前 5 行，避免把全部年份字典当成讲义答案。

### 案例：前 5 行的年份字典


In [3]:
def freq_table(values):
    table = {}
    for value in values:
        if value not in table:
            table[value] = 0
        table[value] = table[value] + 1
    return table

years = []
for row in body[:5]:
    years.append(row[RELEASE_DATE][:4])
year_freq = freq_table(years)
print("First 5 years list:", years)
print("First 5 year freq:", year_freq)
for key in year_freq:
    print("Year key", key, "length", len(key), "count", year_freq[key])


First 5 years list: ['2000', '1999', '2003', '2001', '1999']
First 5 year freq: {'2000': 1, '1999': 2, '2003': 1, '2001': 1}
Year key 2000 length 4 count 1
Year key 1999 length 4 count 2
Year key 2003 length 4 count 1
Year key 2001 length 4 count 1


### 讲解

前 5 行的键应是四位字符串：1999 出现 2 次，其余各 1 次。`len("1999")` 为 4，验收时看的就是这种键。全表年份频率在 P1 用全部 `body` 再做一遍；本格不要把全表字典贴进作答栏。

### 易错点与练习

若忘记 `[:4]`，键会变成完整日期，种类会多得不像“年份表”。

1. **K3.1** 四步里“键不在则置 0”少写时，第一次碰到新的年会怎样？
2. **K3.2** 怎样用 `len(key)` 检查键是不是四位年？

**作答：** 缺置 0：____；四位检查：____。


In [ ]:
# Write your predictions, reasoning, or solution here.
# Keep deliberately faulty snippets in Markdown; run your corrected code here.


## 4. 不能对 int 切片，要先 `str()`

### 理论知识

切片是给**序列**用的：列表、字符串可以；整数不行。好评转换成 `int` 之后，若直接写 `n[0]`，会得到 `TypeError`。档位规则需要“看数字的第一位”，所以先 `str(n)`，再切片。

故障写法只留在文字里：

```python
# Deliberate fault: slicing an int.
n = 3318
print(n[0])
```

### 案例：先变成字符串再取首位


In [4]:
n = 3318
text = str(n)
print(type(n), type(text))
print("First character:", text[0])
print("All characters:", text)
print("124534 as text[:1] / rest length:", str(124534)[0], len(str(124534)) - 1)


<class 'int'> <class 'str'>
First character: 3
All characters: 3318
124534 as text[:1] / rest length: 1 5


### 讲解

`3318` 的类型是 `int`，`str(3318)` 才是 `"3318"`。第一位 `"3"` 后面还有 3 位，档位里要补 3 个 0。`124534` 共 6 位，第一位 `"1"`，后面补 5 个 0。

### 易错点与练习

第 9 课刚把好评转成 int，本课又要转回字符串——这不是走回头路，而是“算术用 int，看位数用 str”。

1. **K4.1** 预测 `n = 3318` 时 `n[0]` 的报错类型。
2. **K4.2** `str(124534)` 的长度是多少？补零应补几个？

**作答：** 对 int 切片：____；124534 的位数与补零：____。


In [ ]:
# Write your predictions, reasoning, or solution here.
# Keep deliberately faulty snippets in Markdown; run your corrected code here.


## 5. 档位规则：首位、补 0、加号

### 理论知识

**档位是为了让频率表可读，不是为了精确算术。** 全班必须同一规则，否则两个人的字典无法对照：

1. 先把好评变成整数，再 `str(...)`。
2. 若只有 1 位，约定为 `"0+"`。
3. 否则：第一位 +（长度-1 个 `"0"`）+ `"+"。

因此 `3318` → `3000+`，`124534` → `100000+`。不要改成四舍五入或自己发明的区间。

### 案例：两个规定例子


In [5]:
def rating_bucket(n):
    text = str(int(n))
    if len(text) == 1:
        return "0+"
    return text[0] + "0" * (len(text) - 1) + "+"

print("3318 ->", rating_bucket(3318))
print("124534 ->", rating_bucket(124534))
print("40 ->", rating_bucket(40))
print("5 ->", rating_bucket(5))


3318 -> 3000+
124534 -> 100000+
40 -> 40+
5 -> 0+


### 讲解

`3318` 变成 `3000+`，`124534` 变成 `100000+`。`40` 是两位，变成 `40+`；个位数走 `"0+"` 分支。P1 的档位频率字典里应能看到 `100000+` 这类键——具体次数你自己统计，讲义不预填全表。

### 易错点与练习

补 0 的个数是 `len(text) - 1`，不是固定 3 个。位数不同的数补错，是本课卡点。

1. **K5.1** `3416` 和 `1273` 按规则各是什么档？
2. **K5.2** 若有人把 `124534` 写成 `12万+`，为什么全班不能混用？

**作答：** 两个档位：____；规则必须统一的原因：____。


In [ ]:
# Write your predictions, reasoning, or solution here.
# Keep deliberately faulty snippets in Markdown; run your corrected code here.


## 6. 对前几行做好评档位

### 理论知识

把档位函数接到数据行上：取出 `positive_ratings`，`int` 之后再 `rating_bucket`。案例仍只走前 5 行。全表档位字典会出现多种键；验收只要求你能在自己算出的字典里看到 `100000+` 这种形式，而不是在题面抄答案。

### 案例：前 5 行的档


In [6]:
print("First 5 rating buckets:")
sample_buckets = []
for row in body[:5]:
    value = int(row[POSITIVE_RATINGS].replace(",", ""))
    bucket = rating_bucket(value)
    sample_buckets.append(bucket)
    print(row[NAME], value, "->", bucket)
print("Bucket freq of first 5:", freq_table(sample_buckets))


First 5 rating buckets:
Counter-Strike 124534 -> 100000+
Team Fortress Classic 3318 -> 3000+
Day of Defeat 3416 -> 3000+
Deathmatch Classic 1273 -> 1000+
Half-Life: Opposing Force 5250 -> 5000+
Bucket freq of first 5: {'100000+': 1, '3000+': 2, '1000+': 1, '5000+': 1}


### 讲解

Counter-Strike 的 124534 进入 `100000+`；Team Fortress Classic 的 3318 进入 `3000+`。前 5 行里 `3000+` 可能不止一次。这只是结构演示。P1 要对全部 `body` 建档位频率表。

### 易错点与练习

好评列若还带着逗号，先按第 9 课去掉再 `int`。不要对原始文本直接切片充当年份或档位。

1. **K6.1** 前 5 行哪一款落入 `100000+`？
2. **K6.2** 全表档位字典应在 P1 用什么循环范围构建？

**作答：** 落入 100000+ 的游戏：____；P1 循环范围：____。


In [ ]:
# Write your predictions, reasoning, or solution here.
# Keep deliberately faulty snippets in Markdown; run your corrected code here.


## 7. 开发者频数：四步再走一遍

### 理论知识

开发者在下标 4。统计出现次数，又是同一套四步。课堂用前 5 行感受“又是那四步”，不要在讲义输出全表 Top5——本课不讲 pandas 排序，也不把 `sorted(..., key=...)` 当成必学语法。需要时，直接打印某个你已经数过的名字的次数。

### 案例：前 5 行里 Valve 出现几次


In [7]:
dev_values = []
for row in body[:5]:
    dev_values.append(row[DEVELOPER])
dev_freq = freq_table(dev_values)
print("First 5 developers:", dev_values)
print("First 5 developer freq:", dev_freq)
print("Valve in first 5:", dev_freq["Valve"])


First 5 developers: ['Valve', 'Valve', 'Valve', 'Valve', 'Gearbox Software']
First 5 developer freq: {'Valve': 4, 'Gearbox Software': 1}
Valve in first 5: 4


### 讲解

前 5 行开发者名单里 Valve 出现 4 次，Gearbox Software 出现 1 次。这句话已经比 `print(dev_freq)` 更像摘要。全表开发者有多少、谁最多，不在本格公布，避免变成 P1 的现成答案。

### 易错点与练习

开发者名字是字符串键，不要用下标 0、1、2 当 keys。样本很小，Valve 多不算“全 Steam 第一”，口径必须写清“前 5 行”。

1. **K7.1** 前 5 行 Valve 的次数是字典里的值，还是键？
2. **K7.2** 为什么本格不打印全表开发者排行？

**作答：** Valve 的次数：____；不 dump 全表的理由：____。


In [ ]:
# Write your predictions, reasoning, or solution here.
# Keep deliberately faulty snippets in Markdown; run your corrected code here.


## 8. 可读摘要，不要只 dump 字典

### 理论知识

**摘要是给人读的句子。** `print(freq)` 对调试有用，但作业和验收还要一句带单位或范围的话。例如：说明统计对象是前 5 行还是全表，说出某个具体键和次数。数字旁边要有含义：年、档、款。

第 10 课是数据分析主线的收束。结论里重复口径：键是四位年；档位按首位补 0 加号。

### 案例：把前 5 行写成两句人话


In [8]:
print("摘要1：前 5 行的发行年包括", years, "其中 1999 年有", year_freq["1999"], "款。")
print("摘要2：前 5 行里 Valve 开发了", dev_freq["Valve"], "款游戏。")
print("摘要3：Counter-Strike 的好评 124534 落入档位", rating_bucket(124534), "。")


摘要1：前 5 行的发行年包括 ['2000', '1999', '2003', '2001', '1999'] 其中 1999 年有 2 款。
摘要2：前 5 行里 Valve 开发了 4 款游戏。
摘要3：Counter-Strike 的好评 124534 落入档位 100000+ 。


### 讲解

三句话都带范围“前 5 行”或具体游戏名，避免听起来像全表结论。P1 换用全表时，句子里的范围也要改成全表，并带上年份键、档位键是否符合验收。

### 易错点与练习

不要把讲义里的前 5 行次数抄成全表答案。全表数字必须重新循环。

1. **K8.1** 把摘要 2 改成全表口径时，要改哪几个词？
2. **K8.2** 验收看年份 keys 是否四位、档位 keys 是否像 `100000+`。只 dump 字典但键是完整日期，能过吗？

**作答：** 口径要改的词：____；键不合格时：____。


In [ ]:
# Write your predictions, reasoning, or solution here.
# Keep deliberately faulty snippets in Markdown; run your corrected code here.


## 综合练习：年份频率、档位与一句话摘要

使用同一份 [steam.csv](steam.csv)。年份键必须是四位年；档位频率字典里应能看到 `100000+` 这类键。不要把全表年份种类数、全表开发者排行写死在题面或代码里——必须打印计算值。不要 dump 全部键值除非你自己需要核对，核对后用一句话摘要收束。

### P1.1　读取并做年份频率

独立读取。确认 `release_date` 下标。对全部数据行取 `[:4]`，用四步（或 `freq_table`）做年份频率。打印若干键，并说明 keys 为什么是四位年。抽查前 5 行手算与字典是否一致（手算不得与全表混比）。


In [ ]:
# P1.1: Read Steam, take four-digit years, and build the year-frequency dict here.


### P1.2　好评档位频率

把 `positive_ratings` 转 int（先去逗号），再按本课规则分档。打印档位字典或其中一部分，指出是否出现 `100000+` 这样的键。

**作答：** 档位规则（一句话）：____；是否见到 100000+：____。


In [ ]:
# P1.2: Build the rating-bucket frequency dict here.


### P1.3　一句话摘要

不要只留下 `print(字典)`。写至少一句可读摘要，包含统计对象（全表）、一个具体年份或档位或开发者，以及次数。重启内核，Run All。

**作答：** 摘要原句：____；年份键是否四位：____；档位键示例：____。


In [ ]:
# P1.3: Write a one-sentence readable summary here.


## 本章总结

1. 字符串可切片：`row[2][:4]` 取四位发行年。
2. 年份频率沿用四步；键必须是四位年。
3. 档位规则：`str` 后取首位、其余补 0、加号；`3318` → `3000+`，`124534` → `100000+`。
4. 不能对 int 切片。
5. 摘要是人话，不是只 dump 字典。

数据分析主线到此暂停。第 11 课转贪吃蛇。若继续用 Steam，先认列、先写口径。

课后请打开 [chapter10_年份切片与摘要_课后练习.ipynb](chapter10_年份切片与摘要_课后练习.ipynb)，使用 [steam_sample.csv](steam_sample.csv) 独立完成 P1、P2（P3 选做）。课后只有 50 条，不能把课堂全表字典抄过去。
